export const FETCH_NEWS = 'FETCH_NEWS';
export const LOAD_MORE_NEWS = 'LOAD_MORE_NEWS';
export const FETCH_NEWS_SUCCESS = 'FETCH_NEWS_SUCCESS';
export const FETCH_NEWS_FAILURE = 'FETCH_NEWS_FAILURE';
export const UPVOTE_NEWS = 'UPVOTE_NEWS';
export const HIDE_NEWS = 'HIDE_NEWS';